# Generated by Django 4.0.5 on 2022-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_remove_avatar_avatar_avatar_image_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatars/avatar.png', null=True, upload_to='avatars'),
        ),
    ]
