# Generated by Django 4.0.5 on 2022-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egreso',
            old_name='nombre',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='nombre',
            new_name='detalle',
        ),
    ]
