# Generated by Django 4.0.5 on 2022-06-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_rename_nombre_egreso_detalle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='detalle',
            new_name='nombre',
        ),
    ]
