# Generated by Django 4.0.4 on 2022-05-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha', models.DateField(verbose_name='%d/%m/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dequien', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha', models.DateField(verbose_name='%d/%m/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=30)),
            ],
        ),
    ]
