# Generated by Django 4.0.4 on 2022-05-29 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos',
            name='monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='egresos',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
