# Generated by Django 4.0.5 on 2022-06-08 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0002_egresos_monto_ingresos_monto_alter_egresos_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('monto', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_quien', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('monto', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RenameModel(
            old_name='personas',
            new_name='Persona',
        ),
        migrations.DeleteModel(
            name='egresos',
        ),
        migrations.DeleteModel(
            name='ingresos',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tipo_egreso',
            old_name='tipos',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='egreso',
            name='tipo_egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_egreso.tipo_egreso'),
        ),
    ]
