# Generated by Django 4.0.5 on 2022-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0003_egreso_ingreso_rename_personas_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='apellido', max_length=30),
            preserve_default=False,
        ),
    ]
