# Generated by Django 4.0.5 on 2022-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0004_persona_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
    ]
