# Generated by Django 4.0.4 on 2022-06-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_egreso', '0006_persona_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='de_quien',
        ),
    ]
